# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
EDITOR=vim
alias grep="grep --color"
alias showvars="set | grep "^\([[:alnum:]]\|[[:punct:]]\)\+=""
alias cmsg="curl -s http://whatthecommit.com/index.txt"
